name: Bug Report
description: Report a bug in the Caffeine DI lib
labels:
  - 'bug'

body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to Reproduce
      placeholder: Please provide a detailed step by step to reproduce the problem and the expected behaviour.

  - type: textarea
    id: exception-or-error
    attributes:
      label: Please provide the exception or error you found

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        Please provide the environment you discovered this bug.

        @caffeine-projects/di: 1.0.0
        Node: 21.6.2
        Package Manager: npm 10.6.0
        OS: linux x64

  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: 'By submitting this issue, I confirm that:'
      options:
        - label: I agree to follow Caffeine Projects DI [Code of Conduct](https://github.com/caffeine-projects/di/blob/main/CODE_OF_CONDUCT.md).
          required: true
        - label: I have checked for existing issues that describe my problem prior to opening this one.
          required: true
