name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - '[0-9]+.x'
    tags:
      - '*'
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package.json

      - name: install
        run: |
          npm install --no-package-lock --ignore-scripts

      - name: lint
        run: |
          npm run fmt:check
          npm run lint
  
      - name: build
        run: |
          npm run build

  test:
    name: test on ${{ matrix.os }} @ ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    needs: build

    permissions:
      contents: read

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        node-version: ['20', 'current']

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package.json

      - name: install
        run: |
          npm install --no-package-lock --ignore-scripts

      - name: test
        run: |
          npm run test:ci
